version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
    # The actions in triage-issues.yml are updated in the Homebrew/.github repo
    ignore:
      - dependency-name: actions/stale
    groups:
      artifacts:
        patterns:
          - actions/*-artifact

  - package-ecosystem: bundler
    directory: /Library/Homebrew
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    groups:
      sorbet:
        patterns:
          - "sorbet*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
